### ISSUE TITLE
Use action hook instead of modifying the index.php file

### ISSUE THREAD

**Issue by francoisjacquet** [dpredster/Access_Log#1]
Hello @dpredster 

Great work!

Since [RosarioSIS 2.9.8](https://github.com/francoisjacquet/rosariosis/blob/mobile/CHANGES.md#changes-in-298) there is a new action tag `index.php|login_check` you can use in a `functions.php` file.
This will let you add your own code without modifying the core file.
Please note that there is only one hook, not one for Users / Students & Failed login. You can check if the `$_SESSION` variables are set and use the [`$username`](https://github.com/francoisjacquet/rosariosis/blob/mobile/index.php#L206) that will be passed to your function (2nd argument).

You will learn more about Action hooks in the new [Starter Guide](https://github.com/francoisjacquet/Example/wiki/Starter-Guide#action-hooks) wiki.

**Comment by dpredster** [comment]
Hi @francoisjacquet 

Thank you for the feedback and wiki. I am working on updating my module to use the action tag.

**Comment by dpredster** [comment]
Hi @francoisjacquet 

I have completed the new version that uses the index.php|login_check action tags. Thank you for all your help.  I look forward to contributing to this project in any way I can.

Please feel free to use or include my module in your work.
